source "https://rubygems.org"
gem "jekyll" , github: "jekyll/jekyll"
gem "jekyll-theme-hydeout", "~> 4.1"
gem "jekyll_github_sample"
gem "jekyll-paginate"
gem "jekyll-feed"
gem "jekyll-remote-theme"
gem "jekyll-sitemap"